### ISSUE TITLE
Legacy color codes in Discord death message

### ISSUE THREAD

**Issue by Cuube** [infinitygrid/Mercury#2]
![image](https://user-images.githubusercontent.com/19961227/123520449-fe104780-d6b0-11eb-9cf8-33a055d9908b.png)

**Comment by HoppelHobbit** [comment]
what are these issues for?

**Comment by l3nnartt** [comment]
ToDo

**Comment by Cuube** [comment]
@HoppelHobbit 
> what are these issues for?

As @l3nnartt mentioned, they're only for my own purposes of noting them down somewhere, so I don't forget. But if, say, any survival participant found an issue/bug, they can create one here as well. The only thing that still needs to be communicated across us and our players is which repository is related to survival, which one is related to our discord bot and which is related to every server and so on. Will do that somewhen, it's a work-in-progress. 😉

**Comment by Cuube** [comment]
Note to self before I sleep: this RegEx might help: `/§[\da-fklmnorx]/gi`
